M48
; DRILL file {KiCad 7.0.9} date 
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-30T12:31:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X89.496Y-107.901
X94.576Y-106.885
X94.576Y-108.917
T2
X94.488Y-113.538
X121.63Y-108.12
T0
M30
